"""Shared visual tokens and global styles for the SOS Drive Reflex app."""

COLORS = {
    "trust_blue": "#1E3A8A",
    "navy": "#0F172A",
    "emergency_orange": "#F97316",
    "orange_dark": "#C2410C",
    "background": "#E2E8F0",
    "surface": "#FFFFFF",
    "text": "#0F172A",
    "muted": "#475569",
    "line": "#CBD5E1",
    "glass": "rgba(255, 255, 255, 0.85)",
    "glass_border": "rgba(255, 255, 255, 0.6)",
    "glass_shadow": "0 10px 30px rgba(15, 23, 42, 0.12)",
}

GLOBAL_STYLE = {
    "background": COLORS["background"],
    "color": COLORS["text"],
    "font_family": "'Inter', 'Space Grotesk', 'Segoe UI', sans-serif",
    "*": {"box_sizing": "border-box"},
    "html": {"margin": "0", "padding": "0", "width": "100%", "height": "100%"},
    "body": {"margin": "0", "padding": "0", "width": "100%", "min_height": "100%"},
    ".app-shell": {
        "min_height": "100vh",
        "background": "radial-gradient(circle at 12% 4%, rgba(249,115,22,.15), transparent 28rem), #E2E8F0",
        "padding": ["1rem", "clamp(1rem, 4vw, 4rem)", "4rem"],
    },
    ".hero-shell": {
        "padding": "clamp(1.25rem, 4vw, 2.5rem)",
        "border_radius": "2rem",
        "background": "linear-gradient(135deg, rgba(255,255,255,.98), rgba(248,250,252,.85))",
        "border": "1px solid rgba(255,255,255,.9)",
        "box_shadow": "0 24px 80px rgba(15,23,42,.12)",
        "overflow": "hidden",
    },
    ".brand-mark": {"display": "grid", "place_items": "center", "width": "2.5rem", "height": "2.5rem", "border_radius": "12px", "background": COLORS["navy"], "color": "white", "font_weight": "900"},
    ".brand-name": {"font_size": "1.2rem", "font_weight": "900", "letter_spacing": "-.04em"},
    ".top-pill": {"padding": ".55rem .85rem", "border": "1px solid rgba(30,58,138,.2)", "border_radius": "999px", "color": COLORS["navy"], "font_size": ".78rem", "font_weight": "800", "background": "rgba(255,255,255,.7)"},
    ".eyebrow, .section-kicker": {"color": COLORS["emergency_orange"], "font_size": ".75rem", "font_weight": "900", "letter_spacing": ".13em", "text_transform": "uppercase"},
    ".eyebrow": {"margin_top": "4rem"},
    ".hero-title": {"font_size": "clamp(3rem, 7vw, 5.5rem)", "line_height": ".95", "font_weight": "900", "letter_spacing": "-.06em"},
    ".hero-copy, .section-intro": {"color": COLORS["muted"], "font_size": "1.05rem", "line_height": "1.6", "max_width": "42rem"},
    ".trust-chip": {"padding": ".58rem .78rem", "border": "1px solid rgba(30,58,138,.2)", "border_radius": "999px", "background": "rgba(255,255,255,.8)", "color": COLORS["navy"], "font_size": ".8rem", "font_weight": "800"},
    ".hero-visual": {"min_height": "27rem", "padding": "1.2rem", "border_radius": "1.75rem", "background": "linear-gradient(145deg, rgba(16,42,67,1), rgba(30,58,138,0.9))", "color": "white", "box_shadow": "0 28px 70px rgba(15,23,42,.3)"},
    ".visual-label": {"color": "#C8E7FA", "font_size": ".7rem", "font_weight": "800", "letter_spacing": ".12em", "text_transform": "uppercase"},
    ".live-label": {"color": "#86EFAC", "font_size": ".75rem"},
    ".map-preview": {"height": "14rem", "margin_y": "1.25rem", "padding": "1rem", "display": "flex", "align_items": "end", "border_radius": "1.25rem", "background": "linear-gradient(32deg, transparent 47%, rgba(255,255,255,.15) 48%, transparent 50%), #1B4A70"},
    ".map-label": {"padding": ".55rem .7rem", "border_radius": "10px", "background": "rgba(11,18,32,.7)", "font_size": ".75rem"},
    ".assist-card": {"padding": "1rem", "border": "1px solid rgba(255,255,255,.25)", "border_radius": "1.25rem", "background": "rgba(255,255,255,.15)"},
    ".assist-icon": {"display": "grid", "place_items": "center", "width": "2.6rem", "height": "2.6rem", "border_radius": "13px", "background": COLORS["emergency_orange"], "color": COLORS["navy"], "font_size": "1.2rem"},
    ".assist-detail": {"color": "#C8E7FA", "font_size": ".8rem"},
    ".mini-stats": {"align_self": "end", "padding": ".7rem .85rem", "border_radius": "14px", "background": "white", "color": COLORS["navy"], "font_size": ".72rem"},
    ".section-title": {"margin_top": "0", "color": COLORS["text"], "font_weight": "900", "letter_spacing": "-.05em"},
    ".info-card, .service-card": {"padding": "1.2rem", "border": f"1px solid {COLORS['line']}", "border_radius": "1.25rem", "background": "white", "box_shadow": "0 4px 6px rgba(0,0,0,0.05)"},
    ".info-card": {"min_height": "10rem"},
    ".step-number": {"color": COLORS["emergency_orange"], "font_size": ".76rem", "font_weight": "900", "letter_spacing": ".12em"},
    ".service-card": {"text_align": "center", "font_weight": "800"},
    ".trust-band": {"padding": "1.35rem", "border_radius": "1.4rem", "background": f"linear-gradient(135deg, {COLORS['navy']}, {COLORS['trust_blue']})", "color": "white"},
    ".bottom-note": {"padding": "1.25rem", "border_radius": "1.4rem", "background": COLORS["navy"], "color": "white", "font_weight": "800"},
    ".primary-button": {"min_height": "3.25rem", "border_radius": "14px", "background": f"linear-gradient(135deg, {COLORS['emergency_orange']}, #FB923C)", "color": "white", "font_weight": "850", "box_shadow": "0 12px 26px rgba(249,115,22,.3)"},
    ".action-button": {"display": "flex", "align_items": "center", "justify_content": "center", "overflow": "visible", "white_space": "nowrap", "text_decoration": "none"},
    ".sos-request-button": {"color": "white", "font_weight": "bold", "filter": "none", "text_shadow": "none", "box_shadow": "none"},
    ".secondary-button": {"min_height": "3.25rem", "border_radius": "14px", "border": f"1px solid {COLORS['line']}", "background": "white", "color": COLORS["navy"], "font_weight": "800", "box_shadow": "0 4px 6px rgba(0,0,0,0.05)", "_hover": {"border_color": COLORS["muted"], "color": COLORS["muted"], "background": "#F8FAFC"}},
    ".text-button": {"padding": "0", "background": "transparent", "color": COLORS["trust_blue"], "font_weight": "800"},
    ".role-card": {"min_height": "5.5rem", "padding": "1rem", "border": f"1px solid {COLORS['line']}", "border_radius": "14px", "background": "white", "color": COLORS["navy"], "text_align": "left"},
    ".role-card.selected": {"border": f"2px solid {COLORS['emergency_orange']}", "background": "#FFF7ED", "box_shadow": "0 8px 20px rgba(249,115,22,.14)"},
    ".role-detail": {"color": COLORS["muted"], "font_size": ".78rem"},
    ".login-panel": {"padding": "clamp(1.25rem, 5vw, 3rem)", "border_radius": "1.5rem", "background": "rgba(255,255,255,.95)", "box_shadow": "0 24px 70px rgba(15,23,42,.15)"},
    ".field-label": {"color": COLORS["navy"], "font_size": ".85rem", "font_weight": "800"},
    ".profile-input": {
        "border": "1px solid transparent",
        "background": "#F1F5F9",
        "color": COLORS["text"],
        "_focus": {"border_color": COLORS["navy"], "outline": "none"},
    },
    ".error-message": {"color": "#B91C1C", "font_size": ".9rem", "font_weight": "700"},
    ".success-message": {"color": "#166534", "font_size": ".9rem", "font_weight": "700"},
    ".glass-panel": {
        "background": COLORS["glass"],
        "backdrop_filter": "blur(16px)",
        "border": f"1px solid {COLORS['glass_border']}",
        "box_shadow": COLORS["glass_shadow"],
        "border_radius": "20px",
    },
    ".op-card": {
        "padding": "1.2rem",
        "background": "white",
        "border_radius": "16px",
        "box_shadow": "0 4px 12px rgba(0,0,0,0.08)",
        "border": f"1px solid {COLORS['line']}",
        "transition": "transform 0.2s, box-shadow 0.2s",
        "_hover": {
            "transform": "translateY(-2px)",
            "box_shadow": "0 8px 20px rgba(0,0,0,0.12)",
            "cursor": "pointer",
        },
    },
    ".user-home-root": {
        "width": "100vw",
        "height": "100vh",
        "background": "white",
        "flex_direction": "column",
        "overflow_y": "auto",
        "@media (min-width: 992px)": {
            "flex_direction": "row",
            "overflow_y": "hidden",
        },
    },
    ".service-details-grid": {
        "grid_template_columns": "1fr",
        "@media (min-width: 992px)": {
            "grid_template_columns": "minmax(0, 1fr) minmax(0, 1fr)",
        },
    },
    "@media (max-width: 720px)": {".top-pill": {"display": "none"}, ".hero-shell": {"border_radius": "1.35rem"}},
    "@media (prefers-reduced-motion: reduce)": {"*": {"transition": "none !important", "animation": "none !important"}},
}
